Repository jumpserver/web-static, pull requests merged in 2024-04, with the labels that each got.

#35 perf: 优化构建
  .github/workflows/check-client-version.yml
  .github/workflows/release.yml
  VERSION
Labels: 类型:优化

#37 perf: 更新客户端
  VERSION
  prepare.sh
Labels: 类型:优化

#40 fix: 添加 applets 依赖
  .github/workflows/jms-build-test.yml
  .github/workflows/release.yml
  .github/workflows/sync-gitea.yml
Labels: 类型:bug

#41 perf: 优化脚本
  prepare.sh
Labels: 类型:优化

#42 feat: remove gitea
  .github/workflows/release.yml
  .github/workflows/sync.yml
Labels: 类型:新功能

#43 perf: 优化 actions 脚本
  .github/workflows/release.yml
  .github/workflows/sync.yml
Labels: 类型:优化

#44 fix: 修正 oss 路径
  .github/workflows/sync.yml
Labels: 类型:bug

#46 feat: 固定版本
  .github/workflows/release.yml
  .github/workflows/sync.yml
Labels: 类型:新功能

#49 perf: 添加 v4
  .github/workflows/check-client-version.yml
Labels: 类型:优化
